spring:
  application:
    name: Amazon

server:
  port: 1010



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1010/eureka}
    fetch-registry: true
    register-with-eureka: true

  instance:
    preferIpAddress: true
